# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, unique=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, unique=True, verbose_name='last_name')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='email')),
                ('avatar_image', models.ImageField(upload_to='avatar/%Y/%m/%d', verbose_name='avatar_image')),
                ('child', models.BooleanField(default=False, verbose_name='child')),
                ('minor', models.BooleanField(default=False, verbose_name='minor')),
                ('adult', models.BooleanField(default=False, verbose_name='child')),
                ('adresse', models.CharField(max_length=100, unique=True, verbose_name='adresse')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='country')),
            ],
        ),
    ]
